### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Mpdreamz** [robinwassen/forcefocus#3]
I am working on a window manager for windows and hit a dead end

When using virtual desktops sometimes the last active window on the desktop your switching too randomly loses focus. A nasty side effect of this is when then switch to another virtual desktop this window starts travelling along the deskop switches and flashing in the taskbar. 

People have gone as far patching `explorer.exe` https://github.com/Ciantic/DisableFlashingTaskbarButtons which is not a route I am comfortable with :). 

I had previously written an [alt+tab replacement for windows](https://github.com/Mpdreamz/tabalt) and could not remember having any issues switching the active window focus. 

Thanks to your project I understand the only reason I had no problems before was by virtue of the `alt` key always being pressed 😸 

Now I forcefully activate the first window (in alt tab order) on desktop switches [using your routine](https://github.com/robinwassen/forcefocus/blob/master/src/forcefocus_win.cc#L26-L39)  and this has improved stability **tremendously**. 

My dead end is squashed and I get to hack on my window manager some more. 

Thank you!

**Comment by robinwassen** [comment]
Hi Martin,

I am glad that the routine managed to solve a problem for you, and I really appreciate that you took the time to write this comment about it. The most common things to hear when building open source stuff is either about bugs or just silence.

Hope you do some good progress on the window manager, feel free to shoot me a message when you want to show it off :)

Regards,
Robin
